# Generated by Django 4.2 on 2024-10-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='colors',
            field=models.CharField(choices=[('viridis', 'viridis'), ('Purples', 'Purples'), ('plasma', 'plasma'), ('viridis', 'viridis'), ('viridis', 'viridis'), ('viridis', 'viridis'), ('viridis', 'viridis'), ('viridis', 'viridis')], default='viridis', max_length=50),
        ),
    ]
